### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by saschagrunert** [opencontainers/runtime-spec#1010]
Hi there,

Do you think it would be possible to tag a new release according to semver? Some go module based dependencies have to rewrite their go.mod to get the latest features in. :innocent:  Thanks in advance! :)

**Comment by cyphar** [comment]
The main thing I'd like to see be ready before a new runtime-spec release is the resolution of #1008 -- which will allow runc to have a 1.0 release.

**Comment by h-vetinari** [comment]
It seems the resolution of #1008 is held up mainly by waiting for someone to review the PR. ;-)

**Comment by onlyjob** [comment]
Formal release is long overdue... Because of that some projects (namely [runtime-tools](https://github.com/opencontainers/runtime-tools/blob/v0.9.0/Godeps/Godeps.json#L37)) already deviated from good practice of vendoring by tag...

**Comment by vbatts** [comment]
to echo @h-vetinari, we are waiting on #1008 for a next release of the spec, and of runc-1.0.0 :grimacing:

**Comment by h-vetinari** [comment]
#1008 has been merged a week ago. Is all that's necessary a PR with a tag? I'm guessing this is better left to the maintainers, but according to several comments all over the place, `runtime-spec 1.0.2` should be ready?

**Comment by vbatts** [comment]
vote for release is posted

**Comment by h-vetinari** [comment]
#1026 failed due to meeting the 2/3 quorum of maintainers; since then, two inactive maintainers have stepped down, meaning the quorum could now be reached with the LGTMs from the last vote alone. Since a nit** was brought up by @kad on the [vote thread](https://groups.google.com/a/opencontainers.org/forum/#!msg/dev/lYFhr-kmSAQ/9QmAI6yVDAAJ) anyway, I thought it'd be good to double-check the state of open PRs - not to further delay the release, but to pick up already finished changes, since runtime-spec releases are few and far between. In descending order of approval:

* #1025; 2 LGTMs; needs rebase to pass spurious CI error
* #1003; 2 LGTMs (including the author @vbatts, who can't approve it from the POV of pullapprove?)
* #978; 1 LGTM
* #975; 1 LGTM
* #937; 1 LGTM; needs rebase


For completeness, the remaining open PRs are probably not ready / necessary for a last-minute merge:
* PRs introducing additional (conditional) `MUSTs`: #680, #934, #935, #939, #946, #982
* TPM support seems reasonably complete but needs at least a rebase: #920
* Repo hygiene: #1027, #1029

-------

**
> @kad: There is one questionable statement introduced by PRs #988 and #932 about Intel RDT closID state, which in theory should require small clarification:
One case that is not covered in the description is 
>
> "If `closID` is set and neither `l3CacheSchema` nor `memBwSchema` is set".
> In this case, I think, runtime should check if closID exists in the resctrl and assign container to it.
> If this closID does not exist in resctl - error.

**Comment by vbatts** [comment]
Good list. Would want to try your hand at carrying over #937 ?

**Comment by h-vetinari** [comment]
Updated the list.

**Comment by h-vetinari** [comment]
All the open PRs that could still be [considered](https://github.com/opencontainers/runtime-spec/issues/1010#issuecomment-581553814) for the next release are exceedingly trivial and could be finished if two devs took half an hour each.

In any case, now that two months have passed since the first quorum, it's really time to get this release done, IMHO.

**Comment by h-vetinari** [comment]
Only two PRs left that could realistically still squeeze into `1.0.2`. If anyone except @tianon (who already LGTM'd) could look at #1034 #1035, there'd be nothing left but to actually release it. :)
@crosbymichael @mrunalp @vbatts @dqminh @hqhq

**Comment by h-vetinari** [comment]
All done; thanks @vbatts! 🎉
Any ETA on sending out the vote?

**Comment by h-vetinari** [comment]
Another week, another ping (I'm sorry for apparently talking to myself here 😅)

**Comment by h-vetinari** [comment]
I don't want to presume that a release-PR from a non-maintainer would be welcome, but in case it is, I have a branch ready that updates #1026 with the changes that have happened since then.

**Comment by vbatts** [comment]
vote posted!
