### ISSUE TITLE
[ Config ] Mounts | type is underspecified

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/runtime-spec#470]
The type parameter is a required string and this is defined for Linux however there is no information for Solaris and there is a suggestion of just using "ntfs" for Windows.  

I don't know how important this parameter is for Linux, but if this is not defined for Solaris and there is only one value for Windows, maybe this should be optional; or required for Linux but otherwise optional?

**Comment by wking** [comment]
On Fri, May 27, 2016 at 09:41:46AM -0700, Rob Dolin (MSFT) wrote:
> I don't know how important this parameter is for Linux… maybe this
> should be optional…

+1 on making it optional.  See this ccon example where I don't set it
for bind mounts [1], and mount(2) describes MS_BIND with [2]:

  The filesystemtype and data arguments are ignored.

Obviously you'll still want to set 'type' when you mount a tmpfs or
some such ;).

[1]: https://github.com/wking/ccon/tree/v0.3.0#mount-namespace
[2]: http://man7.org/linux/man-pages/man2/mount.2.html

**Comment by hqhq** [comment]
Related to https://github.com/opencontainers/runtime-spec/issues/303 , I'm tagging `1.0.0`, any Solaris guys around?

**Comment by jlbutler** [comment]
I believe this issue has been addressed via commits from @hqhq (https://github.com/opencontainers/runtime-spec/commit/1752ce8b12486fdcabfaddc1878113c3ff489d59) and @anuthan (https://github.com/opencontainers/runtime-spec/commit/07b7958b7e5e66b716de0aec875953bec8535be4).

@RobDolinMS could you respond with whether or not this needs more work for Windows?

**Comment by jhowardmsft** [comment]
Looking at the first commit, I would strongly prefer type to be optional on Windows. It is not required.

**Comment by jlbutler** [comment]
@jhowardmsft does that mean that type is optional entirely, or if not supplied that the runtime implementation defaults to 'ntfs' and fills in the value in configuration metadata?

If the latter, I'd prefer we leave it as a REQUIRED field, where the implementation has a usability feature of filling a default in. If the type of file system is truly optional, that's a different story.

Note this passage has updated since the commit referenced above. It's still set REQUIRED but the description optionally allows for different filesystem types.
