### ISSUE TITLE
Please tag 0.5.1 (and keep tagging releases)

### ISSUE THREAD

**Issue by onlyjob** [opencontainers/runtime-spec#497]
Fix incorporated into [runc v0.1.1](https://github.com/opencontainers/runc/releases/tag/v0.1.1) qualifies for minor release of _runtime-spec_. Please tag.

**Comment by wking** [comment]
On Sat, Jun 11, 2016 at 05:23:13PM -0700, Dmitry Smirnov wrote:
> Fix incorporated into [runc
> v0.1.1](https://github.com/opencontainers/runc/releases/tag/v0.1.1)
> qualifies for minor release of _runtime-spec_. Please tag.

Which fix is that?  runtime-spec cut v1.0.0-rc1 on 2016-06-03 [1], and
that landed in runC on the same day [2].  I'm not aware of anyone
planning to continue patch releases of the v0.5 line.

[1]: https://github.com/opencontainers/runtime-spec/pull/486#issuecomment-223708952
[2]: https://github.com/opencontainers/runc/pull/876#event-681735313

**Comment by onlyjob** [comment]
In Debian we can't upgrade _runc_ because (its dependency) _runtime-spec_ is not updated. As you may know _runtime-spec_ is packaged separately (currently at version 0.5.0) and uploading RC version is not ideal... Hence tagging 0.5.1 would be helpful.

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 12:15:45AM -0700, Dmitry Smirnov wrote:
> As you may know _runtime-spec_ is packaged separately (currently at
> version 0.5.0) and uploading RC version is not ideal...

opencontainers/runc#746 bumped the spec dependency to 0.5.0 just
before cutting runC 0.1.0.  Since there have been no non-RC spec
releases since then, subsequent runC releases have been based on
random snapshots pulled from spec development.  I don't think there
will be any more OCI releases until opencontainers/tob#15 gets sorted
[1], so waiting for 1.0s is probably about the same amount of time as
waiting for a 0.6.0 spec release and runC work targetting it.

[1]: http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2016/opencontainers.2016-06-08-17.01.log.html#l-97

**Comment by vbatts** [comment]
@onlyjob sorry. Does the https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc1 tag suffice for now?

**Comment by onlyjob** [comment]
That would probably work, thank you. :)

Though I prefer semantic tags and tagging 0.5.1 (not as far away from 0.5.0 as 1.0.0~rc1) might be even better...

Here you can read more about semantic versioning:

 * [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).
 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning
