### ISSUE TITLE
the runtime-spec should be Closure

### ISSUE THREAD

**Issue by laijs** [opencontainers/runtime-spec#593]
Closure: https://en.wikipedia.org/wiki/Closure_(mathematics)

A: any of the runtime-spec described items
B: any of the runtime-spec described APIs about A

A \* B = C
operate B on A and result item C

C should be one of the runtime-spec described items.
and we should not allow any other operation on A.

ref: https://github.com/opencontainers/runc/issues/1137
and an example in it when A=the pid.

**Comment by crosbymichael** [comment]
Since this issue has not received any feedback or have any actionable items in it I think it is safe to close.

When making issues you should clearly state your problem, a proposed solution, and what it solves.  There is not much to take from this issue or anywhere to go from its title or description in regards to the OCI runtime spec.  That could be a reason why it has not received any feedback from anyone.
