### ISSUE TITLE
Incorrect description about device cgroups

### ISSUE THREAD

**Issue by dongsupark** [opencontainers/runtime-spec#983]
The section of [devices whitelist in the spec](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#device-whitelist) says:

> allow (boolean, REQUIRED) - whether the entry is allowed or denied.

Apparently it expects container runtime to add the entry to the whitelist if `allow` is true, and add the entry to the blacklist if `allow` is false.

However, that's not exactly a correct description about device cgroups, according to the [document in the Linux Kernel](https://github.com/torvalds/linux/blob/master/Documentation/cgroup-v1/devices.txt). In fact, writing to `devices.allow` results in adding the entry to the whitelist, while writing to `devices.deny` results in removing the entry from the whitelist. For example:

```
# mkdir /sys/fs/cgroup/devices/t1
# echo a > /sys/fs/cgroup/devices/t1/devices.deny   # clean up the whitelist
# cat /sys/fs/cgroup/devices/t1/devices.list
# echo 'c 1:3 rw' > /sys/fs/cgroup/devices/t1/devices.allow  # add a single entry to the whitelist
# cat /sys/fs/cgroup/devices/t1/devices.list
c 1:3 rw
# echo 'c 1:3 rw' > /sys/fs/cgroup/devices/t1/devices.deny  # remove the entry from the whitelist
# cat /sys/fs/cgroup/devices/t1/devices.list  # there's no entry left
```

So I think that we should just remove the `allow` field in the spec, to only deal with simple whitelist cases. Or is there any better way?

Also we should explicitly mention that `access` field must not be an empty string, `""`.
For example `echo 'c 1:3 ' > /sys/fs/cgroup/devices/t1/devices.allow` will fail with -EINVAL.

**Comment by flx42** [comment]
I'm not sure I understand the problem here. I read this as: if `allow` is true, right the entry to `devices.allow`, otherwise write the entry to `devices.deny`. 

> So I think that we should just remove the allow field in the spec, to only deal with simple whitelist cases.

The spec does not seem to mandate any default whitelist, and combined with `cgroupsPath` it seems we do need to be able to add **and** remove to the whitelist.

**Comment by dongsupark** [comment]
Thanks for the clarification.
Ok, maybe I was misunderstanding these words.
Then instead of removing the allow part, how about explaining explicitly that it's about adding & removing to the whitelist?

**Comment by crosbymichael** [comment]
I don't think the spec is a document to explain system level details.  It should be generic as much as possible.  Allow, allows this device.

**Comment by cyphar** [comment]
In theory the most we should do it just point people to the documentation of the cgroup controller. In general we prefer to avoid defining specific kernel behaviour because it's out of the control of the runtime how kernel behaviour works (and most runtime-spec options are just piped directly into kernel APIs).

**Comment by dongsupark** [comment]
I see. Thanks for comments.
